# Generated by Django 6.0.6 on 2026-08-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_categoria_producto_descripcion_producto_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
